-- Create the customer master table
CREATE TABLE IF NOT EXISTS customers (
    Customer_ID VARCHAR(20) PRIMARY KEY,
    Customer_Name VARCHAR(100),
    Age INT,
    Gender VARCHAR(20),
    City VARCHAR(50),
    State VARCHAR(50),
    Customer_Since DATE,
    Customer_Segment VARCHAR(30),
    KYC_Status VARCHAR(20),
    Home_Device_ID_1 VARCHAR(30),
    Home_Device_ID_2 VARCHAR(30),
    Baseline_Avg_Amount DECIMAL(15,2)
);

-- Create the transactions table
CREATE TABLE IF NOT EXISTS transactions (
    Transaction_ID VARCHAR(30) PRIMARY KEY,
    Transaction_Timestamp DATETIME,
    Transaction_Date DATE,
    Transaction_Time TIME,
    Customer_ID VARCHAR(20),
    Account_ID VARCHAR(30),
    Merchant_ID VARCHAR(30),
    Payment_Method VARCHAR(30),
    Transaction_Type VARCHAR(50),
    Amount DECIMAL(15,2),
    Transaction_Status VARCHAR(20),
    Device_Type VARCHAR(30),
    Device_ID VARCHAR(30),
    Location VARCHAR(100),
    State VARCHAR(50),
    IP_Address VARCHAR(50),
    Network_Type VARCHAR(30),
    Transaction_Channel VARCHAR(30),
    Previous_Transaction_Time DATETIME,
    Time_Since_Last_Transaction_Min DECIMAL(10,2),
    Velocity_10Min_Count INT,
    Customer_Avg_Amount DECIMAL(15,2),
    Amount_Deviation_Pct DECIMAL(10,2),
    New_Device_Flag TINYINT,
    Location_Mismatch_Flag TINYINT,
    Geo_Distance_KM DECIMAL(10,2),
    Unusual_Hour_Flag TINYINT,
    IP_Mismatch_Flag TINYINT,
    Failed_Burst_Flag TINYINT,
    Merchant_Risk_Flag TINYINT,
    Fraud_Flag TINYINT,
    Fraud_Reason VARCHAR(100),
    Risk_Score INT,
    Risk_Level VARCHAR(20),
    FOREIGN KEY (Customer_ID) REFERENCES customers(Customer_ID)
);
